# Generated by Django 5.1.7 on 2025-03-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_drinkcategory_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkCategory',
            new_name='DrinksCategory',
        ),
    ]
