# Generated by Django 5.1.7 on 2025-04-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_employee_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
