# Generated by Django 5.1.7 on 2025-04-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_employee2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employee2',
        ),
    ]
