# Generated by Django 5.1.7 on 2025-04-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_delete_employee_delete_employee2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.AlterField(
            model_name='drinks',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.drinkscategory'),
        ),
    ]
